name: Update README

on:
  push:
    branches:
      - main
  schedule:
    # Runs every first and 12 hrs.
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add activity to readme
        uses: jamesgeorge007/github-activity-readme@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: fanyang89
          COMMIT_MSG: "docs(readme): update recent activity"
          MAX_LINES: 20
          FILTER_EVENTS: PullRequestEvent
          TARGET_FILE: README.md
